Repository eclipse/xtext-extras, pull requests merged in 2018-10, with the labels that each got.

#307 [eclipse/xtext#1272] Remove signature workaround
  gradle/bootstrap-setup.gradle
Labels: releng

#309 [eclipse/xtext#1300] Update to Gradle Wrapper 4.10.2
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
Labels: releng

#306 [eclipse/xtext#1222] Auto-detect upstream repository URLs
  build.gradle
  gradle/upstream-repositories.gradle
Labels: enhancement, releng

#312 [#311] Use consistent encoding in CompilationTestHelper
  org.eclipse.xtext.xbase.testing/src/org/eclipse/xtext/xbase/testing/CompilationTestHelper.java
Labels: enhancement

#310 [eclipse/xtext#1280] made genManifest / genSourcesManifest gradle 5 ready
  gradle/manifest-gen.gradle
Labels: releng

#314 [eclipse/xtext#1222] fixed branch detection on Jenkins
  gradle/upstream-repositories.gradle
Labels: releng

#316 [eclipse/xtext-umbrella#65] Adjust upstream branch
  releng/pom.xml
Labels: releng

#321 [eclipse/xtext#1321] bootstrap against 2.16.0.M1
  gradle/versions.gradle
Labels: releng

#325 [eclipse/xtext#1315] removed p2gen
  build.gradle
  gradle/p2-deployment.gradle
Labels: releng

#326 Updated xtext-gradle-plugin to 2.0.2
  gradle/versions.gradle
Labels: releng

#327 [eclipse/xtext#1325] switch to ASM 7
  gradle/versions.gradle
  org.eclipse.xtext.common.types.tests/META-INF/MANIFEST.MF_gen
  org.eclipse.xtext.common.types/META-INF/MANIFEST.MF
  org.eclipse.xtext.common.types/src/org/eclipse/xtext/common/types/access/binary/asm/JvmAnnotationReferenceBuilder.java
  org.eclipse.xtext.common.types/src/org/eclipse/xtext/common/types/access/binary/asm/JvmAnnotationValueBuilder.java
  org.eclipse.xtext.common.types/src/org/eclipse/xtext/common/types/access/binary/asm/JvmDeclaredTypeBuilder.java
  org.eclipse.xtext.common.types/src/org/eclipse/xtext/common/types/access/binary/asm/JvmExecutableBuilder.java
  org.eclipse.xtext.common.types/src/org/eclipse/xtext/common/types/access/binary/asm/JvmFieldBuilder.java
  org.eclipse.xtext.generator/src/org/eclipse/xtext/generator/types/TypesGeneratorFragment.java
  org.eclipse.xtext.purexbase.tests/META-INF/MANIFEST.MF
  org.eclipse.xtext.purexbase/META-INF/MANIFEST.MF
  org.eclipse.xtext.xbase.ide/META-INF/MANIFEST.MF
  org.eclipse.xtext.xbase.testdata/META-INF/MANIFEST.MF
  org.eclipse.xtext.xbase.testlanguages/META-INF/MANIFEST.MF
  org.eclipse.xtext.xbase/META-INF/MANIFEST.MF
Labels: releng
