Repository eclipse/xtext-extras, pull requests merged in 2019-06, with the labels that each got.

#435 [eclipse/xtext#1463] Increase timeout to 60 minutes
  Jenkinsfile
Labels: releng

#436 [eclipse/xtext#1463] Increase timeout to 60 minutes
  CBI.Jenkinsfile
Labels: releng

#437 [eclipse/xtext#1474] Prepare Master for 2.19
  gradle/versions.gradle
  org.eclipse.xtext.builder.standalone.tests/META-INF/MANIFEST.MF
  org.eclipse.xtext.builder.standalone/META-INF/MANIFEST.MF
  org.eclipse.xtext.common.types.tests/META-INF/MANIFEST.MF
  org.eclipse.xtext.common.types/META-INF/MANIFEST.MF
  org.eclipse.xtext.ecore/META-INF/MANIFEST.MF
  org.eclipse.xtext.extras.tests/META-INF/MANIFEST.MF
  org.eclipse.xtext.generator/META-INF/MANIFEST.MF
  org.eclipse.xtext.java.tests/META-INF/MANIFEST.MF
  org.eclipse.xtext.java/META-INF/MANIFEST.MF
  org.eclipse.xtext.purexbase.ide/META-INF/MANIFEST.MF
  org.eclipse.xtext.purexbase.tests/META-INF/MANIFEST.MF
  org.eclipse.xtext.purexbase/META-INF/MANIFEST.MF
  org.eclipse.xtext.smap/META-INF/MANIFEST.MF
  org.eclipse.xtext.xbase.ide/META-INF/MANIFEST.MF
  org.eclipse.xtext.xbase.testdata/META-INF/MANIFEST.MF
  org.eclipse.xtext.xbase.testing/META-INF/MANIFEST.MF
  org.eclipse.xtext.xbase.testlanguages.ide/META-INF/MANIFEST.MF
  org.eclipse.xtext.xbase.testlanguages/META-INF/MANIFEST.MF
  org.eclipse.xtext.xbase.tests/META-INF/MANIFEST.MF
  org.eclipse.xtext.xbase/META-INF/MANIFEST.MF
  releng/p2/category.xml
  releng/p2/pom.xml
  releng/pom.xml
  releng/releng-target/pom.xml
Labels: releng

#439 [eclipse/xtext#1475] build against orbit 2019-09
  releng/releng-target/xtext-extras.target.target
Labels: releng

#438 [eclipse/xtext#1473] bootstrap against 2.18
  gradle/versions.gradle
Labels: releng

#442 [eclipse/xtext#1463] Configure timeout & timestamps
  CBI.Jenkinsfile
  Jenkinsfile
Labels: releng

#444 [eclipse/xtext#1485] update to mwe 2.11
  releng/releng-target/xtext-extras.target.target
Labels: releng

#450 bumped grgit plugin
  build.gradle
Labels: releng

#451 [eclipse/xtext#1431] Enhance container support
  1-gradle-build.sh
  3-gradle-longrunning-tests.sh
  CBI.Jenkinsfile
Labels: releng

#452 [eclipse/xtext#1490] Bump xtext-gradle-plugin to 2.0.5
  gradle/versions.gradle
Labels: releng

#449 [#445] Fixed scoping in try-with-resources
  org.eclipse.xtext.purexbase.tests/src/org/eclipse/xtext/xbase/junit/evaluation/AbstractXbaseEvaluationTest.java
  org.eclipse.xtext.xbase.testing/testdata/testdata/AbstractClosableWithList.xtend
  org.eclipse.xtext.xbase.testing/xtend-gen/testdata/AbstractClosableWithList.java
  org.eclipse.xtext.xbase.testing/xtend-gen/testdata/ClosableWithList.java
  org.eclipse.xtext.xbase.testing/xtend-gen/testdata/ClosableWithListExceptionOnAdd.java
  org.eclipse.xtext.xbase.testing/xtend-gen/testdata/ClosableWithListExceptionOnClose.java
  org.eclipse.xtext.xbase.testing/xtend-gen/testdata/ClosableWithListExceptionOnConstr.java
  org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/typesystem/computation/XbaseTypeComputer.java
Labels: bug

#454 [eclipse/xtext-xtend#818] Add classgraph to target platform
  org.eclipse.xtext.common.types/META-INF/MANIFEST.MF
  org.eclipse.xtext.common.types/src/org/eclipse/xtext/common/types/descriptions/ClasspathScanner.xtend
  org.eclipse.xtext.common.types/xtend-gen/org/eclipse/xtext/common/types/descriptions/ClasspathScanner.java
  releng/releng-target/xtext-extras.target.target
Labels: enhancement

#455 [eclipse/xtext-core#1178] Use one 1 cpu in every pod
  CBI.Jenkinsfile
Labels: releng

#456 bumped io.spring.dependency-management plugin
  gradle/versions.gradle
Labels: releng

#457 [eclipse/xtext#1495] Use unique label for each agent
  CBI.Jenkinsfile
Labels: releng

#459 [eclipse/xtext#1431] Tweak resource constraints
  CBI.Jenkinsfile
Labels: releng

#461 [#343] Workaround for NPE in TypeReferenceOwner
  org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/compiler/XbaseCompiler.java
Labels: bug
