Repository eclipse/xtext-extras, pull requests merged in 2019-12, with the labels that each got.

#536 [releng] Update Xtext version to 2.21.0
  gradle/versions.gradle
  org.eclipse.xtext.builder.standalone.tests/META-INF/MANIFEST.MF
  org.eclipse.xtext.builder.standalone/META-INF/MANIFEST.MF
  org.eclipse.xtext.common.types.tests/META-INF/MANIFEST.MF
  org.eclipse.xtext.common.types/META-INF/MANIFEST.MF
  org.eclipse.xtext.ecore/META-INF/MANIFEST.MF
  org.eclipse.xtext.extras.tests/META-INF/MANIFEST.MF
  org.eclipse.xtext.generator/META-INF/MANIFEST.MF
  org.eclipse.xtext.java.tests/META-INF/MANIFEST.MF
  org.eclipse.xtext.java/META-INF/MANIFEST.MF
  org.eclipse.xtext.purexbase.ide/META-INF/MANIFEST.MF
  org.eclipse.xtext.purexbase.tests/META-INF/MANIFEST.MF
  org.eclipse.xtext.purexbase/META-INF/MANIFEST.MF
  org.eclipse.xtext.smap/META-INF/MANIFEST.MF
  org.eclipse.xtext.xbase.ide/META-INF/MANIFEST.MF
  org.eclipse.xtext.xbase.testdata/META-INF/MANIFEST.MF
  org.eclipse.xtext.xbase.testing/META-INF/MANIFEST.MF
  org.eclipse.xtext.xbase.testlanguages.ide/META-INF/MANIFEST.MF
  org.eclipse.xtext.xbase.testlanguages/META-INF/MANIFEST.MF
  org.eclipse.xtext.xbase.tests/META-INF/MANIFEST.MF
  org.eclipse.xtext.xbase/META-INF/MANIFEST.MF
  releng/p2/category.xml
  releng/p2/pom.xml
  releng/pom.xml
  releng/releng-target/pom.xml
Labels: bot, releng

#539 [releng] Bootstrap against 2.20.0
  gradle/versions.gradle
Labels: bot, releng

#541 [#540] Re-export org.eclipse.xtext to not break downstream projects
  org.eclipse.xtext.ecore/META-INF/MANIFEST.MF
Labels: bug

#543 Kt xtend issue942 suppress modifiers
  org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/compiler/JvmModelGenerator.xtend
  org.eclipse.xtext.xbase/xtend-gen/org/eclipse/xtext/xbase/compiler/JvmModelGenerator.java
Labels: enhancement
