Repository eclipse/xtext-extras, pull requests merged in 2019-05, with the labels that each got.

#417 [eclipse/xtext#1440] Update to ASM 7.1.0.
  org.eclipse.xtext.common.types.tests/META-INF/MANIFEST.MF_gen
  org.eclipse.xtext.common.types/META-INF/MANIFEST.MF
  org.eclipse.xtext.generator/src/org/eclipse/xtext/generator/types/TypesGeneratorFragment.java
  org.eclipse.xtext.purexbase.tests/META-INF/MANIFEST.MF
  org.eclipse.xtext.purexbase/META-INF/MANIFEST.MF
  org.eclipse.xtext.xbase.ide/META-INF/MANIFEST.MF
  org.eclipse.xtext.xbase.testdata/META-INF/MANIFEST.MF
  org.eclipse.xtext.xbase.testlanguages/META-INF/MANIFEST.MF
  org.eclipse.xtext.xbase/META-INF/MANIFEST.MF
  releng/releng-target/xtext-extras.target.target
Labels: releng

#418 disable parallel
  CBI.Jenkinsfile
Labels: releng

#420 [eclipse/xtext#1427] disable p2 mirrors
  2-maven-build.sh
Labels: releng

#361 [eclipse/xtext#1384] Change Jenkinsfile to Declarative Pipeline
  Jenkinsfile
Labels: releng

#423 [eclipse/xtext#1437] Bootstrap against 2.18.0.M2
  gradle/versions.gradle
  org.eclipse.xtext.generator/xtend-gen/org/eclipse/xtext/generator/parser/antlr/XtextAntlrGeneratorComparisonFragment.java
  org.eclipse.xtext.xbase.ide/xtend-gen/org/eclipse/xtext/xbase/ide/types/ClasspathScanner.java
  org.eclipse.xtext.xbase.tests/xtend-gen/org/eclipse/xtext/xbase/tests/compiler/JvmModelGeneratorTest.java
  org.eclipse.xtext.xbase/xtend-gen/org/eclipse/xtext/xbase/controlflow/ConstantConditionsInterpreter.java
Labels: releng

#422 update to gradle 5.4.1
  gradle/wrapper/gradle-wrapper.properties
Labels: releng

#427 Fixed exception with Java11
  org.eclipse.xtext.common.types/src/org/eclipse/xtext/common/types/access/reflect/ReflectionTypeFactory.java
Labels: bug

#429 [#424] fixed test fails with java 11
  org.eclipse.xtext.common.types.tests/tests/org/eclipse/xtext/common/types/access/impl/AbstractTypeProviderTest.java
  org.eclipse.xtext.java.tests/src/org/eclipse/xtext/common/types/access/impl/AbstractTypeProviderTest.java
  org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/compiler/JvmModelGeneratorTest.xtend
  org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/typesystem/ResolvedOperationTest.xtend
  org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/typing/XbaseTypeProviderTest.java
  org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/util/ClasspathScannerTest.xtend
  org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/validation/XbaseValidationTest.xtend
  org.eclipse.xtext.xbase.tests/xtend-gen/org/eclipse/xtext/xbase/tests/compiler/JvmModelGeneratorTest.java
  org.eclipse.xtext.xbase.tests/xtend-gen/org/eclipse/xtext/xbase/tests/typesystem/ResolvedOperationTest.java
  org.eclipse.xtext.xbase.tests/xtend-gen/org/eclipse/xtext/xbase/tests/util/ClasspathScannerTest.java
  org.eclipse.xtext.xbase.tests/xtend-gen/org/eclipse/xtext/xbase/tests/validation/XbaseValidationTest.java
Labels: bug

#433 Use classgraph library to scan classpath contents
  org.eclipse.xtext.common.types/build.gradle
  org.eclipse.xtext.common.types/src/org/eclipse/xtext/common/types/descriptions/ClasspathScanner.xtend
  org.eclipse.xtext.common.types/src/org/eclipse/xtext/common/types/descriptions/ClasspathTypeDescriptor.xtend
  org.eclipse.xtext.common.types/src/org/eclipse/xtext/common/types/descriptions/ITypeDescriptor.xtend
  org.eclipse.xtext.common.types/xtend-gen/org/eclipse/xtext/common/types/descriptions/ClasspathScanner.java
  org.eclipse.xtext.common.types/xtend-gen/org/eclipse/xtext/common/types/descriptions/ClasspathTypeDescriptor.java
  org.eclipse.xtext.common.types/xtend-gen/org/eclipse/xtext/common/types/descriptions/ITypeDescriptor.java
  org.eclipse.xtext.xbase.ide/META-INF/MANIFEST.MF
  org.eclipse.xtext.xbase.ide/src/org/eclipse/xtext/xbase/ide/DefaultXbaseIdeModule.xtend
  org.eclipse.xtext.xbase.ide/src/org/eclipse/xtext/xbase/ide/contentassist/ClasspathBasedIdeTypesProposalProvider.xtend
  org.eclipse.xtext.xbase.ide/src/org/eclipse/xtext/xbase/ide/contentassist/IIdeTypesProposalProvider.xtend
  org.eclipse.xtext.xbase.ide/src/org/eclipse/xtext/xbase/ide/contentassist/TypeFilters.xtend
  org.eclipse.xtext.xbase.ide/src/org/eclipse/xtext/xbase/ide/contentassist/XbaseIdeContentProposalPriorities.xtend
  org.eclipse.xtext.xbase.ide/src/org/eclipse/xtext/xbase/ide/contentassist/XbaseIdeContentProposalProvider.xtend
  org.eclipse.xtext.xbase.ide/src/org/eclipse/xtext/xbase/ide/types/ClasspathScanner.xtend
  org.eclipse.xtext.xbase.ide/src/org/eclipse/xtext/xbase/ide/types/ClasspathTypeDescriptor.xtend
  org.eclipse.xtext.xbase.ide/xtend-gen/org/eclipse/xtext/xbase/ide/DefaultXbaseIdeModule.java
  org.eclipse.xtext.xbase.ide/xtend-gen/org/eclipse/xtext/xbase/ide/contentassist/ClasspathBasedIdeTypesProposalProvider.java
  org.eclipse.xtext.xbase.ide/xtend-gen/org/eclipse/xtext/xbase/ide/contentassist/IIdeTypesProposalProvider.java
  org.eclipse.xtext.xbase.ide/xtend-gen/org/eclipse/xtext/xbase/ide/contentassist/TypeFilters.java
  org.eclipse.xtext.xbase.ide/xtend-gen/org/eclipse/xtext/xbase/ide/contentassist/XbaseIdeContentProposalPriorities.java
  org.eclipse.xtext.xbase.ide/xtend-gen/org/eclipse/xtext/xbase/ide/contentassist/XbaseIdeContentProposalProvider.java
  org.eclipse.xtext.xbase.ide/xtend-gen/org/eclipse/xtext/xbase/ide/types/ClasspathScanner.java
  org.eclipse.xtext.xbase.ide/xtend-gen/org/eclipse/xtext/xbase/ide/types/ClasspathTypeDescriptor.java
  org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/util/ClasspathScannerTest.xtend
  org.eclipse.xtext.xbase.tests/xtend-gen/org/eclipse/xtext/xbase/tests/util/ClasspathScannerTest.java
Labels: enhancement

#434 [releng] Prepare migration to JIRO
  CBI.Jenkinsfile
  Jenkinsfile
Labels: releng
