Repository eclipse/xtext-extras, pull requests merged in 2019-04, with the labels that each got.

#400 [eclipse/xtext#1424] Change default Jenkins
  README.md
  gradle/bootstrap-setup.gradle
  gradle/upstream-repositories.gradle
  releng/pom.xml
Labels: releng

#401 Use mavenCentral instead of jcenter to avoid sync delays and stability issues
  build.gradle
  gradle/bootstrap-setup.gradle
  gradle/upstream-repositories.gradle
  releng/pom.xml
Labels: releng

#402 replaced tf jenkins with ci.eclipse.org/xtext for lsp4j
  gradle/upstream-repositories.gradle
Labels: releng

#404 [eclipse/xtext#1173] set discouraged access to warning
  org.eclipse.xtext.java.tests/.settings/org.eclipse.jdt.core.prefs
  org.eclipse.xtext.purexbase.tests/.settings/org.eclipse.jdt.core.prefs
  org.eclipse.xtext.xbase.tests/.settings/org.eclipse.jdt.core.prefs
Labels: releng

#405 [eclipse/xtext#1309] Provide Jenkinsfile for Eclipse CBI
  1-gradle-build.sh
  2-maven-build.sh
  3-gradle-longrunning-tests.sh
  CBI.Jenkinsfile
  releng/pom.xml
Labels: releng

#407 [xtext-xtend#734] Fixed restore logic of runtime injector providers
  org.eclipse.xtext.common.types.tests/src-gen/org/eclipse/xtext/common/types/xtext/ui/tests/RefactoringTestLanguageInjectorProvider.java
  org.eclipse.xtext.extras.tests/src/org/eclipse/xtext/tests/XtextInjectorProvider.java
  org.eclipse.xtext.purexbase.ide/src-gen/org/eclipse/xtext/purexbase/ide/AbstractPureXbaseIdeModule.java
  org.eclipse.xtext.purexbase.tests/src-gen/org/eclipse/xtext/purexbase/tests/PureXbaseInjectorProvider.java
  org.eclipse.xtext.purexbase/src-gen/org/eclipse/xtext/purexbase/serializer/PureXbaseSyntacticSequencer.java
  org.eclipse.xtext.xbase.testlanguages/src-gen/org/eclipse/xtext/xbase/testlanguages/bug462047/tests/Bug462047LangInjectorProvider.java
  org.eclipse.xtext.xbase.testlanguages/src-gen/org/eclipse/xtext/xbase/testlanguages/tests/ContentAssistFragmentTestLangInjectorProvider.java
  org.eclipse.xtext.xbase.testlanguages/src-gen/org/eclipse/xtext/xbase/testlanguages/tests/XImportSectionTestLangInjectorProvider.java
  org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/XbaseInjectorProvider.java
Labels: bug

#409 [#403] Fixed regression in injector provider
  org.eclipse.xtext.common.types.tests/src-gen/org/eclipse/xtext/common/types/xtext/ui/tests/RefactoringTestLanguageInjectorProvider.java
  org.eclipse.xtext.extras.tests/src/org/eclipse/xtext/tests/XtextInjectorProvider.java
  org.eclipse.xtext.purexbase.tests/src-gen/org/eclipse/xtext/purexbase/tests/PureXbaseInjectorProvider.java
  org.eclipse.xtext.xbase.testlanguages/src-gen/org/eclipse/xtext/xbase/testlanguages/bug462047/tests/Bug462047LangInjectorProvider.java
  org.eclipse.xtext.xbase.testlanguages/src-gen/org/eclipse/xtext/xbase/testlanguages/tests/ContentAssistFragmentTestLangInjectorProvider.java
  org.eclipse.xtext.xbase.testlanguages/src-gen/org/eclipse/xtext/xbase/testlanguages/tests/XImportSectionTestLangInjectorProvider.java
  org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/XbaseInjectorProvider.java
  org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/validation/EqualsWithNullTest.java
Labels: bug

#410 [eclipse/xtext#1422] update to tycho 1.4.0
  releng/pom.xml
Labels: releng

#412 [eclipse/xtext#1434] Explicit agent configuration
  CBI.Jenkinsfile
Labels: releng

#403 [xtext-eclipse#397] Support for ternary expressions and try with resource
  org.eclipse.xtext.common.types/META-INF/MANIFEST.MF
  org.eclipse.xtext.purexbase.ide/src-gen/org/eclipse/xtext/purexbase/ide/contentassist/antlr/PureXbaseParser.java
  org.eclipse.xtext.purexbase.ide/src-gen/org/eclipse/xtext/purexbase/ide/contentassist/antlr/internal/InternalPureXbase.g
  org.eclipse.xtext.purexbase.ide/src-gen/org/eclipse/xtext/purexbase/ide/contentassist/antlr/internal/InternalPureXbase.tokens
  org.eclipse.xtext.purexbase.ide/src-gen/org/eclipse/xtext/purexbase/ide/contentassist/antlr/internal/InternalPureXbaseLexer.java
  org.eclipse.xtext.purexbase.ide/src-gen/org/eclipse/xtext/purexbase/ide/contentassist/antlr/internal/InternalPureXbaseParser.java
  org.eclipse.xtext.purexbase.tests/src/org/eclipse/xtext/purexbase/test/PureXbaseInterpreterTest.xtend
  org.eclipse.xtext.purexbase.tests/src/org/eclipse/xtext/purexbase/test/XbaseIntegrationTest.java
  org.eclipse.xtext.purexbase.tests/src/org/eclipse/xtext/xbase/junit/evaluation/AbstractXbaseEvaluationTest.java
  org.eclipse.xtext.purexbase.tests/xtend-gen/org/eclipse/xtext/purexbase/test/PureXbaseInterpreterTest.java
  org.eclipse.xtext.purexbase/src-gen/org/eclipse/xtext/purexbase/PureXbase.xtextbin
  org.eclipse.xtext.purexbase/src-gen/org/eclipse/xtext/purexbase/parser/antlr/internal/InternalPureXbase.g
  org.eclipse.xtext.purexbase/src-gen/org/eclipse/xtext/purexbase/parser/antlr/internal/InternalPureXbase.tokens
  org.eclipse.xtext.purexbase/src-gen/org/eclipse/xtext/purexbase/parser/antlr/internal/InternalPureXbaseLexer.java
  org.eclipse.xtext.purexbase/src-gen/org/eclipse/xtext/purexbase/parser/antlr/internal/InternalPureXbaseParser.java
  org.eclipse.xtext.purexbase/src-gen/org/eclipse/xtext/purexbase/serializer/PureXbaseSemanticSequencer.java
  org.eclipse.xtext.purexbase/src-gen/org/eclipse/xtext/purexbase/serializer/PureXbaseSyntacticSequencer.java
  org.eclipse.xtext.purexbase/src-gen/org/eclipse/xtext/purexbase/services/PureXbaseGrammarAccess.java
  org.eclipse.xtext.purexbase/src/org/eclipse/xtext/purexbase/PureXbase.xtext
  org.eclipse.xtext.xbase.testing/testdata/testdata/AbstractClosableWithList.xtend
  org.eclipse.xtext.xbase.testing/testdata/testdata/AbstractIntrospectableClosable.xtend
  org.eclipse.xtext.xbase.testing/xtend-gen/testdata/AbstractClosableWithList.java
  org.eclipse.xtext.xbase.testing/xtend-gen/testdata/AbstractIntrospectableClosable.java
  org.eclipse.xtext.xbase.testing/xtend-gen/testdata/ClosableWithList.java
  org.eclipse.xtext.xbase.testing/xtend-gen/testdata/ClosableWithListExceptionOnAdd.java
  org.eclipse.xtext.xbase.testing/xtend-gen/testdata/ClosableWithListExceptionOnClose.java
  org.eclipse.xtext.xbase.testing/xtend-gen/testdata/ClosableWithListExceptionOnConstr.java
  org.eclipse.xtext.xbase.testing/xtend-gen/testdata/CloseException.java
  org.eclipse.xtext.xbase.testing/xtend-gen/testdata/IntrospectableClosable.java
  org.eclipse.xtext.xbase.testing/xtend-gen/testdata/IntrospectableClosableExceptionsClose.java
  org.eclipse.xtext.xbase.testing/xtend-gen/testdata/IntrospectableClosableExceptionsConstructor.java
  org.eclipse.xtext.xbase.testing/xtend-gen/testdata/TryBodyException.java
  org.eclipse.xtext.xbase/emf-gen/org/eclipse/xtext/xbase/XIfExpression.java
  org.eclipse.xtext.xbase/emf-gen/org/eclipse/xtext/xbase/XTryCatchFinallyExpression.java
  org.eclipse.xtext.xbase/emf-gen/org/eclipse/xtext/xbase/XbasePackage.java
  org.eclipse.xtext.xbase/emf-gen/org/eclipse/xtext/xbase/impl/XIfExpressionImpl.java
  org.eclipse.xtext.xbase/emf-gen/org/eclipse/xtext/xbase/impl/XTryCatchFinallyExpressionImpl.java
  org.eclipse.xtext.xbase/emf-gen/org/eclipse/xtext/xbase/impl/XbasePackageImpl.java
  org.eclipse.xtext.xbase/generator/org/eclipse/xtext/xbase/GenerateXbase.java
  org.eclipse.xtext.xbase/model/Xbase.ecore
  org.eclipse.xtext.xbase/model/Xbase.genmodel
  org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/compiler/AbstractXbaseCompiler.java
  org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/compiler/XbaseCompiler.java
  org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/interpreter/impl/XbaseInterpreter.java
  org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/typesystem/computation/XbaseTypeComputer.java
  org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/typesystem/util/ExtendedEarlyExitComputer.java
  org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/typesystem/util/IThrownExceptionDelegate.java
  org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/typesystem/util/ThrownExceptionSwitch.java
  org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/validation/IssueCodes.java
Labels: new_feature
