Repository eclipse/xtext-extras, pull requests merged in 2019-11, with the labels that each got.

#510 [eclipse/xtext#1569] reduced usage of xtend in purexbase
  org.eclipse.xtext.purexbase.ide/.classpath
  org.eclipse.xtext.purexbase.ide/build.properties
  org.eclipse.xtext.purexbase.ide/src/org/eclipse/xtext/purexbase/ide/PureXbaseIdeModule.java
  org.eclipse.xtext.purexbase.ide/src/org/eclipse/xtext/purexbase/ide/PureXbaseIdeModule.xtend
  org.eclipse.xtext.purexbase.ide/src/org/eclipse/xtext/purexbase/ide/PureXbaseIdeSetup.java
  org.eclipse.xtext.purexbase.ide/src/org/eclipse/xtext/purexbase/ide/PureXbaseIdeSetup.xtend
  org.eclipse.xtext.purexbase/src/org/eclipse/xtext/purexbase/GeneratePureXbase.mwe2
  org.eclipse.xtext.purexbase/src/org/eclipse/xtext/purexbase/PureXbaseRuntimeModule.java
  org.eclipse.xtext.purexbase/src/org/eclipse/xtext/purexbase/PureXbaseStandaloneSetup.java
  org.eclipse.xtext.purexbase/src/org/eclipse/xtext/purexbase/PureXbaseStandaloneSetup.xtend
  org.eclipse.xtext.purexbase/src/org/eclipse/xtext/purexbase/scoping/PureXbaseScopeProvider.java
  org.eclipse.xtext.purexbase/src/org/eclipse/xtext/purexbase/validation/PureXbaseValidator.java
  org.eclipse.xtext.purexbase/src/org/eclipse/xtext/purexbase/validation/PureXbaseValidator.xtend
  org.eclipse.xtext.purexbase/xtend-gen/org/eclipse/xtext/purexbase/PureXbaseRuntimeModule.java
  org.eclipse.xtext.purexbase/xtend-gen/org/eclipse/xtext/purexbase/scoping/PureXbaseScopeProvider.java
  org.eclipse.xtext.purexbase/xtend-gen/org/eclipse/xtext/purexbase/validation/PureXbaseValidator.java
Labels: refactoring

#511 [#419] Incorporated review feedback
  org.eclipse.xtext.java/src/org/eclipse/xtext/java/resource/ClassFileCache.xtend
  org.eclipse.xtext.java/xtend-gen/org/eclipse/xtext/java/resource/ClassFileCache.java
Labels: bug

#512 [eclipse/xtext#1573] Ensure that all plugins do have a ManifestBuilder
  gradle/eclipse-project-layout.gradle
  org.eclipse.xtext.builder.standalone.tests/.project
  org.eclipse.xtext.builder.standalone/.project
  org.eclipse.xtext.common.types.tests/.project
  org.eclipse.xtext.common.types/.project
  org.eclipse.xtext.ecore/.project
  org.eclipse.xtext.extras.tests/.project
  org.eclipse.xtext.extras.tests/META-INF/MANIFEST.MF
  org.eclipse.xtext.generator/.project
  org.eclipse.xtext.java.tests/.project
  org.eclipse.xtext.java.tests/META-INF/MANIFEST.MF
  org.eclipse.xtext.java/.project
  org.eclipse.xtext.purexbase.ide/.classpath
  org.eclipse.xtext.purexbase.ide/.project
  org.eclipse.xtext.purexbase.ide/META-INF/MANIFEST.MF
  org.eclipse.xtext.purexbase.tests/.project
  org.eclipse.xtext.purexbase.tests/META-INF/MANIFEST.MF
  org.eclipse.xtext.purexbase/.project
  org.eclipse.xtext.purexbase/META-INF/MANIFEST.MF
  org.eclipse.xtext.smap/.project
  org.eclipse.xtext.xbase.ide/.project
  org.eclipse.xtext.xbase.testdata/.project
  org.eclipse.xtext.xbase.testdata/META-INF/MANIFEST.MF
  org.eclipse.xtext.xbase.testing/.project
  org.eclipse.xtext.xbase.testlanguages.ide/.project
  org.eclipse.xtext.xbase.testlanguages/.project
  org.eclipse.xtext.xbase.testlanguages/META-INF/MANIFEST.MF
  org.eclipse.xtext.xbase.tests/.project
  org.eclipse.xtext.xbase/.project
Labels: releng

#515 [releng] Bootstrap against 2.20.0.M2
  gradle/versions.gradle
Labels: bot, releng

#518 added gradle properties
  gradle.properties
Labels: releng

#525 cleanup versions.gradle
  gradle/versions.gradle
Labels: releng

#527 updated grgit gradle plugin to version 4.0.0
  build.gradle
Labels: releng

#520 [eclipse/xtext#1569] Refactor Xtend to Java
  org.eclipse.xtext.common.types/.classpath
  org.eclipse.xtext.common.types/build.properties
  org.eclipse.xtext.common.types/src/org/eclipse/xtext/common/types/descriptions/ClasspathScanner.java
  org.eclipse.xtext.common.types/src/org/eclipse/xtext/common/types/descriptions/ClasspathScanner.xtend
  org.eclipse.xtext.common.types/src/org/eclipse/xtext/common/types/descriptions/ClasspathTypeDescriptor.java
  org.eclipse.xtext.common.types/src/org/eclipse/xtext/common/types/descriptions/ClasspathTypeDescriptor.xtend
  org.eclipse.xtext.common.types/src/org/eclipse/xtext/common/types/descriptions/ITypeDescriptor.java
  org.eclipse.xtext.common.types/src/org/eclipse/xtext/common/types/descriptions/ITypeDescriptor.xtend
  org.eclipse.xtext.common.types/src/org/eclipse/xtext/common/types/descriptions/TypeResourceDescription.java
  org.eclipse.xtext.common.types/src/org/eclipse/xtext/common/types/descriptions/TypeResourceDescription.xtend
  org.eclipse.xtext.common.types/xtend-gen/org/eclipse/xtext/common/types/descriptions/ClasspathScanner.java
  org.eclipse.xtext.common.types/xtend-gen/org/eclipse/xtext/common/types/descriptions/ClasspathTypeDescriptor.java
  org.eclipse.xtext.common.types/xtend-gen/org/eclipse/xtext/common/types/descriptions/TypeResourceDescription.java
Labels: refactoring

#521 [eclipse/xtext#1569] Refactor Xtend to Java
  org.eclipse.xtext.builder.standalone.tests/src/org/eclipse/xtext/builder/standalone/incremental/ResourceURICollectorTest.java
  org.eclipse.xtext.builder.standalone/.settings/org.eclipse.jdt.ui.prefs
  org.eclipse.xtext.builder.standalone/src/org/eclipse/xtext/builder/standalone/ClusteringConfig.java
  org.eclipse.xtext.builder.standalone/src/org/eclipse/xtext/builder/standalone/ClusteringConfig.xtend
  org.eclipse.xtext.builder.standalone/src/org/eclipse/xtext/builder/standalone/StandaloneBuilderModule.java
  org.eclipse.xtext.builder.standalone/src/org/eclipse/xtext/builder/standalone/StandaloneBuilderModule.xtend
  org.eclipse.xtext.builder.standalone/src/org/eclipse/xtext/builder/standalone/compiler/CompilerConfiguration.java
  org.eclipse.xtext.builder.standalone/src/org/eclipse/xtext/builder/standalone/compiler/CompilerConfiguration.xtend
  org.eclipse.xtext.builder.standalone/src/org/eclipse/xtext/builder/standalone/incremental/ResourceURICollector.java
  org.eclipse.xtext.builder.standalone/src/org/eclipse/xtext/builder/standalone/incremental/ResourceURICollector.xtend
  org.eclipse.xtext.builder.standalone/xtend-gen/org/eclipse/xtext/builder/standalone/ClusteringConfig.java
  org.eclipse.xtext.builder.standalone/xtend-gen/org/eclipse/xtext/builder/standalone/StandaloneBuilderModule.java
  org.eclipse.xtext.builder.standalone/xtend-gen/org/eclipse/xtext/builder/standalone/compiler/CompilerConfiguration.java
  org.eclipse.xtext.builder.standalone/xtend-gen/org/eclipse/xtext/builder/standalone/incremental/ResourceURICollector.java
Labels: refactoring

#528 moved mwe deps to build.properties
  org.eclipse.xtext.common.types/META-INF/MANIFEST.MF
  org.eclipse.xtext.common.types/build.properties
  org.eclipse.xtext.xbase.testlanguages/META-INF/MANIFEST.MF
  org.eclipse.xtext.xbase.testlanguages/build.properties
Labels: releng

#533 [releng] Bootstrap against 2.20.0.M3
  gradle/versions.gradle
Labels: bot, releng

#534 [eclipse/xtext#1304] Remove XtextVersionTests
  org.eclipse.xtext.extras.tests/src/org/eclipse/xtext/util/XtextVersionTests.java
Labels: refactoring
