Repository eclipse/xtext-extras, pull requests merged in 2020-07, with the labels that each got.

#625 [#624] Fixed scoping for inner classes
  org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/typesystem/internal/LogicalContainerAwareReentrantTypeResolver.java
Labels: bug

#628 [releng] Bootstrap against 2.23.0.M1
  gradle/versions.gradle
Labels: bot, releng

#631 [eclipse/xtext#1777] ported test code to java
  org.eclipse.xtext.purexbase.tests/src/org/eclipse/xtext/purexbase/test/DefaultImportsConfigurationTest.java
  org.eclipse.xtext.purexbase.tests/src/org/eclipse/xtext/purexbase/test/DefaultImportsConfigurationTest.xtend
  org.eclipse.xtext.purexbase.tests/xtend-gen/org/eclipse/xtext/purexbase/test/DefaultImportsConfigurationTest.java
  org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/jvmmodel/JvmModelAssociatorTest.java
  org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/jvmmodel/JvmModelAssociatorTest.xtend
  org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/jvmmodel/JvmTypesBuilderTest.xtend
  org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/typesystem/ResolvedFeaturesTest.java
  org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/typesystem/ResolvedFeaturesTest.xtend
  org.eclipse.xtext.xbase.tests/xtend-gen/org/eclipse/xtext/xbase/tests/jvmmodel/JvmModelAssociatorTest.java
  org.eclipse.xtext.xbase.tests/xtend-gen/org/eclipse/xtext/xbase/tests/jvmmodel/JvmTypesBuilderTest.java
  org.eclipse.xtext.xbase.tests/xtend-gen/org/eclipse/xtext/xbase/tests/typesystem/ResolvedFeaturesTest.java
Labels: releng

#632 [eclipse/xtext#1816] harmonize includeSource to true in preparation for tycho 2.0
  releng/releng-target/xtext-extras.target.target
Labels: releng
