Repository eclipse/xtext-extras, pull requests merged in 2020-05, with the labels that each got.

#597 [eclipse/xtext-core#1462] Regenerated languages
  org.eclipse.xtext.purexbase/src-gen/org/eclipse/xtext/purexbase/parser/antlr/internal/InternalPureXbase.g
  org.eclipse.xtext.purexbase/src-gen/org/eclipse/xtext/purexbase/parser/antlr/internal/InternalPureXbaseParser.java
  org.eclipse.xtext.xbase.testlanguages/src-gen/org/eclipse/xtext/xbase/testlanguages/bug462047/parser/antlr/internal/InternalBug462047Lang.g
  org.eclipse.xtext.xbase.testlanguages/src-gen/org/eclipse/xtext/xbase/testlanguages/bug462047/parser/antlr/internal/InternalBug462047LangParser.java
  org.eclipse.xtext.xbase.testlanguages/src-gen/org/eclipse/xtext/xbase/testlanguages/parser/antlr/internal/InternalContentAssistFragmentTestLang.g
  org.eclipse.xtext.xbase.testlanguages/src-gen/org/eclipse/xtext/xbase/testlanguages/parser/antlr/internal/InternalContentAssistFragmentTestLangParser.java
  org.eclipse.xtext.xbase.testlanguages/src-gen/org/eclipse/xtext/xbase/testlanguages/parser/antlr/internal/InternalXImportSectionTestLang.g
  org.eclipse.xtext.xbase.testlanguages/src-gen/org/eclipse/xtext/xbase/testlanguages/parser/antlr/internal/InternalXImportSectionTestLangParser.java
  org.eclipse.xtext.xbase/src-gen/org/eclipse/xtext/xbase/annotations/parser/antlr/internal/InternalXbaseWithAnnotations.g
  org.eclipse.xtext.xbase/src-gen/org/eclipse/xtext/xbase/annotations/parser/antlr/internal/InternalXbaseWithAnnotationsParser.java
  org.eclipse.xtext.xbase/src-gen/org/eclipse/xtext/xbase/parser/antlr/internal/InternalXbase.g
  org.eclipse.xtext.xbase/src-gen/org/eclipse/xtext/xbase/parser/antlr/internal/InternalXbaseParser.java
  org.eclipse.xtext.xbase/src-gen/org/eclipse/xtext/xbase/parser/antlr/internal/InternalXtype.g
  org.eclipse.xtext.xbase/src-gen/org/eclipse/xtext/xbase/parser/antlr/internal/InternalXtypeParser.java
  org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/impl/XAbstractFeatureCallImplCustom.java
  org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/linking/XbaseLazyLinker.java
Labels: bug

#600 [releng] Bootstrap against 2.22.0.M2
  gradle/versions.gradle
Labels: bot, releng

#602 [eclipse/xtext#1738] removed no longer needed icu dependency
  org.eclipse.xtext.generator/META-INF/MANIFEST.MF
  org.eclipse.xtext.purexbase/build.properties
  org.eclipse.xtext.xbase/META-INF/MANIFEST.MF
Labels: releng

#604 [eclipse/xtext#1765] update to MWE 2.11.3.M3
  releng/releng-target/xtext-extras.target.target
Labels: releng

#608 [eclipse/xtext#1770] update to mwe 2.11.3 final
  releng/releng-target/xtext-extras.target.target
Labels: releng

#605 Removed jnlp image name from pod template
  Jenkinsfile
Labels: releng

#611 [releng] Bootstrap against 2.22.0.M3
  gradle/versions.gradle
Labels: bot, releng
