Repository eclipse/xtext-extras, pull requests merged in 2020-12, with the labels that each got.

#673 [releng] Bootstrap against 2.24.0
  gradle/versions.gradle
Labels: bot, releng

#677 [eclipse/xtext#1652] Use https instead of git URL for SCM connection
  gradle/maven-deployment.gradle
  org.eclipse.xtext.java.tests/build.gradle
  org.eclipse.xtext.smap/build.gradle
  org.eclipse.xtext.xbase.tests/build.gradle
Labels: releng

#680 Do not flag serialVersionUID as unused
  org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/typesystem/internal/LogicalContainerAwareReentrantTypeResolver.java
Labels: new_feature

#675 [eclipse/xtext#1882][2021-03] Update Orbit
  releng/releng-target/xtext-extras.target.target
Labels: releng
