Repository eclipse/xtext-extras, pull requests merged in 2022-09, with the labels that each got.

#799 [eclipse/xtext#2097] remove java nature from project roots
  .classpath
  .project
  .settings/org.eclipse.jdt.core.prefs
  gradle/bootstrap-setup.gradle
Labels: releng

#800 [eclipse/xtext#2099] added missing org.eclipse.jdt.core.prefs
  org.eclipse.xtext.builder.standalone.tests/.settings/org.eclipse.jdt.core.prefs
  org.eclipse.xtext.builder.standalone/.settings/org.eclipse.jdt.core.prefs
  org.eclipse.xtext.common.types.tests/.settings/org.eclipse.jdt.core.prefs
  org.eclipse.xtext.common.types/.settings/org.eclipse.jdt.core.prefs
  org.eclipse.xtext.ecore/.settings/org.eclipse.jdt.core.prefs
  org.eclipse.xtext.extras.tests/.settings/org.eclipse.jdt.core.prefs
  org.eclipse.xtext.generator/.settings/org.eclipse.jdt.core.prefs
  org.eclipse.xtext.purexbase/.settings/org.eclipse.jdt.core.prefs
  org.eclipse.xtext.smap/.settings/org.eclipse.jdt.core.prefs
  org.eclipse.xtext.xbase.ide/.settings/org.eclipse.jdt.core.prefs
  org.eclipse.xtext.xbase.testlanguages.ide/.settings/org.eclipse.jdt.core.prefs
  org.eclipse.xtext.xbase.testlanguages/.settings/org.eclipse.jdt.core.prefs
  org.eclipse.xtext.xbase/.settings/org.eclipse.jdt.core.prefs
Labels: releng

#801 [eclipse/xtext#2089] Update to Orbit 2022-12 incl new classgraph & gson
  NOTICE.md
  org.eclipse.xtext.common.types/META-INF/MANIFEST.MF
  releng/releng-target/xtext-extras.target.target
Labels: releng

#807 [#806] Fixed NPE in Xbase compiler with broken models
  org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/compiler/CompilerTest.java
  org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/compiler/AbstractXbaseCompiler.java
  org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/compiler/FeatureCallCompiler.java
  org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/compiler/XbaseCompiler.java
  org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/compiler/output/SharedAppendableState.java
Labels: bug

#804 [#803] Fixed imported names for Xbase languages
  org.eclipse.xtext.xbase.testlanguages.ide/src-gen/org/eclipse/xtext/xbase/testlanguages/ide/contentassist/antlr/ContentAssistFragmentTestLangParser.java
  org.eclipse.xtext.xbase.testlanguages.ide/src-gen/org/eclipse/xtext/xbase/testlanguages/ide/contentassist/antlr/XImportSectionTestLangParser.java
  org.eclipse.xtext.xbase.testlanguages.ide/src-gen/org/eclipse/xtext/xbase/testlanguages/ide/contentassist/antlr/internal/InternalContentAssistFragmentTestLang.g
  org.eclipse.xtext.xbase.testlanguages.ide/src-gen/org/eclipse/xtext/xbase/testlanguages/ide/contentassist/antlr/internal/InternalContentAssistFragmentTestLang.tokens
  org.eclipse.xtext.xbase.testlanguages.ide/src-gen/org/eclipse/xtext/xbase/testlanguages/ide/contentassist/antlr/internal/InternalContentAssistFragmentTestLangLexer.java
  org.eclipse.xtext.xbase.testlanguages.ide/src-gen/org/eclipse/xtext/xbase/testlanguages/ide/contentassist/antlr/internal/InternalContentAssistFragmentTestLangParser.java
  org.eclipse.xtext.xbase.testlanguages.ide/src-gen/org/eclipse/xtext/xbase/testlanguages/ide/contentassist/antlr/internal/InternalXImportSectionTestLang.g
  org.eclipse.xtext.xbase.testlanguages.ide/src-gen/org/eclipse/xtext/xbase/testlanguages/ide/contentassist/antlr/internal/InternalXImportSectionTestLangLexer.java
  org.eclipse.xtext.xbase.testlanguages.ide/src-gen/org/eclipse/xtext/xbase/testlanguages/ide/contentassist/antlr/internal/InternalXImportSectionTestLangParser.java
  org.eclipse.xtext.xbase.testlanguages/model/generated/ContentAssistFragmentTestLang.ecore
  org.eclipse.xtext.xbase.testlanguages/model/generated/ContentAssistFragmentTestLang.genmodel
  org.eclipse.xtext.xbase.testlanguages/model/generated/XImportSectionTestLang.ecore
  org.eclipse.xtext.xbase.testlanguages/model/generated/XImportSectionTestLang.genmodel
  org.eclipse.xtext.xbase.testlanguages/src-gen/org/eclipse/xtext/xbase/testlanguages/ContentAssistFragmentTestLang.xtextbin
  org.eclipse.xtext.xbase.testlanguages/src-gen/org/eclipse/xtext/xbase/testlanguages/XImportSectionTestLang.xtextbin
  org.eclipse.xtext.xbase.testlanguages/src-gen/org/eclipse/xtext/xbase/testlanguages/contentAssistFragmentTestLang/ContentAssistFragmentTestLangFactory.java
  org.eclipse.xtext.xbase.testlanguages/src-gen/org/eclipse/xtext/xbase/testlanguages/contentAssistFragmentTestLang/ContentAssistFragmentTestLangPackage.java
  org.eclipse.xtext.xbase.testlanguages/src-gen/org/eclipse/xtext/xbase/testlanguages/contentAssistFragmentTestLang/ContentAssistFragmentTestLanguageRoot.java
  org.eclipse.xtext.xbase.testlanguages/src-gen/org/eclipse/xtext/xbase/testlanguages/contentAssistFragmentTestLang/Entity.java
  org.eclipse.xtext.xbase.testlanguages/src-gen/org/eclipse/xtext/xbase/testlanguages/contentAssistFragmentTestLang/impl/ContentAssistFragmentTestLangFactoryImpl.java
  org.eclipse.xtext.xbase.testlanguages/src-gen/org/eclipse/xtext/xbase/testlanguages/contentAssistFragmentTestLang/impl/ContentAssistFragmentTestLangPackageImpl.java
  org.eclipse.xtext.xbase.testlanguages/src-gen/org/eclipse/xtext/xbase/testlanguages/contentAssistFragmentTestLang/impl/ContentAssistFragmentTestLanguageRootImpl.java
  org.eclipse.xtext.xbase.testlanguages/src-gen/org/eclipse/xtext/xbase/testlanguages/contentAssistFragmentTestLang/impl/EntityImpl.java
  org.eclipse.xtext.xbase.testlanguages/src-gen/org/eclipse/xtext/xbase/testlanguages/contentAssistFragmentTestLang/util/ContentAssistFragmentTestLangAdapterFactory.java
  org.eclipse.xtext.xbase.testlanguages/src-gen/org/eclipse/xtext/xbase/testlanguages/contentAssistFragmentTestLang/util/ContentAssistFragmentTestLangSwitch.java
  org.eclipse.xtext.xbase.testlanguages/src-gen/org/eclipse/xtext/xbase/testlanguages/parser/antlr/internal/InternalContentAssistFragmentTestLang.g
  org.eclipse.xtext.xbase.testlanguages/src-gen/org/eclipse/xtext/xbase/testlanguages/parser/antlr/internal/InternalContentAssistFragmentTestLang.tokens
  org.eclipse.xtext.xbase.testlanguages/src-gen/org/eclipse/xtext/xbase/testlanguages/parser/antlr/internal/InternalContentAssistFragmentTestLangLexer.java
  org.eclipse.xtext.xbase.testlanguages/src-gen/org/eclipse/xtext/xbase/testlanguages/parser/antlr/internal/InternalContentAssistFragmentTestLangParser.java
  org.eclipse.xtext.xbase.testlanguages/src-gen/org/eclipse/xtext/xbase/testlanguages/parser/antlr/internal/InternalXImportSectionTestLang.g
  org.eclipse.xtext.xbase.testlanguages/src-gen/org/eclipse/xtext/xbase/testlanguages/parser/antlr/internal/InternalXImportSectionTestLangLexer.java
  org.eclipse.xtext.xbase.testlanguages/src-gen/org/eclipse/xtext/xbase/testlanguages/parser/antlr/internal/InternalXImportSectionTestLangParser.java
  org.eclipse.xtext.xbase.testlanguages/src-gen/org/eclipse/xtext/xbase/testlanguages/serializer/ContentAssistFragmentTestLangSemanticSequencer.java
  org.eclipse.xtext.xbase.testlanguages/src-gen/org/eclipse/xtext/xbase/testlanguages/serializer/XImportSectionTestLangSemanticSequencer.java
  org.eclipse.xtext.xbase.testlanguages/src-gen/org/eclipse/xtext/xbase/testlanguages/services/ContentAssistFragmentTestLangGrammarAccess.java
  org.eclipse.xtext.xbase.testlanguages/src-gen/org/eclipse/xtext/xbase/testlanguages/services/XImportSectionTestLangGrammarAccess.java
  org.eclipse.xtext.xbase.testlanguages/src-gen/org/eclipse/xtext/xbase/testlanguages/xImportSectionTestLang/ImportSectionTestLanguageRoot.java
  org.eclipse.xtext.xbase.testlanguages/src-gen/org/eclipse/xtext/xbase/testlanguages/xImportSectionTestLang/XImportSectionTestLangPackage.java
  org.eclipse.xtext.xbase.testlanguages/src-gen/org/eclipse/xtext/xbase/testlanguages/xImportSectionTestLang/impl/ImportSectionTestLanguageRootImpl.java
  org.eclipse.xtext.xbase.testlanguages/src-gen/org/eclipse/xtext/xbase/testlanguages/xImportSectionTestLang/impl/XImportSectionTestLangPackageImpl.java
  org.eclipse.xtext.xbase.testlanguages/src/org/eclipse/xtext/xbase/testlanguages/ContentAssistFragmentTestLang.xtext
  org.eclipse.xtext.xbase.testlanguages/src/org/eclipse/xtext/xbase/testlanguages/GenerateXbaseTestLanguages.mwe2
  org.eclipse.xtext.xbase.testlanguages/src/org/eclipse/xtext/xbase/testlanguages/XImportSectionTestLang.xtext
  org.eclipse.xtext.xbase.testlanguages/src/org/eclipse/xtext/xbase/testlanguages/XImportSectionTestLangRuntimeModule.java
  org.eclipse.xtext.xbase.testlanguages/src/org/eclipse/xtext/xbase/testlanguages/jvmmodel/ContentAssistFragmentTestLangJvmModelInferrer.java
  org.eclipse.xtext.xbase.testlanguages/src/org/eclipse/xtext/xbase/testlanguages/jvmmodel/XImportSectionTestLangJvmModelInferrer.java
  org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/resources/AbstractXbaseImportedNamesTest.java
  org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/resources/ExtendedXbaseResourceDescriptionStrategyTest.java
  org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/resources/XImportSectionResourceDescriptionStrategyTest.java
  org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/resources/XbaseResourceDescriptionStrategyTest.java
  org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/DefaultXbaseRuntimeModule.java
  org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/resource/XbaseResourceDescription.java
  org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/resource/XbaseResourceDescriptionManager.java
  org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/scoping/XImportSectionNamespaceScopeProvider.java
  org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/scoping/batch/DelegatingScopes.java
  org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/scoping/batch/TypeScopes.java
Labels: bug

#810 [#809] Reduce code duplication in Xbase tests
  org.eclipse.xtext.purexbase.tests/META-INF/MANIFEST.MF
  org.eclipse.xtext.purexbase.tests/src/org/eclipse/xtext/purexbase/test/data/Shape.java
  org.eclipse.xtext.purexbase.tests/src/org/eclipse/xtext/purexbase/tests/CompilerTest.java
  org.eclipse.xtext.purexbase.tests/src/org/eclipse/xtext/purexbase/tests/DefaultImportsConfigurationTest.java
  org.eclipse.xtext.purexbase.tests/src/org/eclipse/xtext/purexbase/tests/ParserTest.java
  org.eclipse.xtext.purexbase.tests/src/org/eclipse/xtext/purexbase/tests/PureXbaseInterpreterTest.java
  org.eclipse.xtext.purexbase.tests/src/org/eclipse/xtext/purexbase/tests/PureXbaseParsingTest.java
  org.eclipse.xtext.purexbase.tests/src/org/eclipse/xtext/purexbase/tests/RuntimeInjectorProvider.java
  org.eclipse.xtext.purexbase.tests/src/org/eclipse/xtext/purexbase/tests/XbaseIntegrationTest.java
  org.eclipse.xtext.purexbase.tests/src/org/eclipse/xtext/purexbase/tests/data/Amount.java
  org.eclipse.xtext.purexbase.tests/src/org/eclipse/xtext/purexbase/tests/data/Circle.java
  org.eclipse.xtext.purexbase.tests/src/org/eclipse/xtext/purexbase/tests/data/Person.java
  org.eclipse.xtext.purexbase.tests/src/org/eclipse/xtext/purexbase/tests/data/Rectangle.java
  org.eclipse.xtext.purexbase.tests/src/org/eclipse/xtext/purexbase/tests/data/Shape.java
  org.eclipse.xtext.purexbase.tests/src/org/eclipse/xtext/xbase/junit/evaluation/AbstractXbaseEvaluationTest.java
  org.eclipse.xtext.xbase.testing/src/org/eclipse/xtext/xbase/testing/evaluation/AbstractXbaseEvaluationTest.java
  org.eclipse.xtext.xbase.tests/longrunning/src/org/eclipse/xtext/xbase/tests/compiler/EvaluationCompilerTest.java
  org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/junit/evaluation/AbstractXbaseEvaluationTest.java
  org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/compiler/CompilerTest.java
  org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/interpreter/XbaseInterpreterTest.java
  org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/serializer/XbaseSerializerWithNodeModelTest.java
  org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/serializer/XbaseSerializerWithoutNodeModelTest.java
  org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/compiler/AbstractXbaseCompiler.java
  org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/compiler/FeatureCallCompiler.java
Labels: technical_debt

#811 [#805] Incremental standalone builds
  org.eclipse.xtext.builder.standalone.tests/META-INF/MANIFEST.MF
  org.eclipse.xtext.builder.standalone.tests/build.gradle
  org.eclipse.xtext.builder.standalone.tests/src/org/eclipse/xtext/builder/standalone/StandaloneBuilderTest.java
  org.eclipse.xtext.builder.standalone.tests/src/org/eclipse/xtext/builder/standalone/TestEclipseCompiler.java
  org.eclipse.xtext.builder.standalone.tests/src/org/eclipse/xtext/builder/standalone/TestIncrementalEclipseCompiler.java
  org.eclipse.xtext.builder.standalone.tests/src/org/eclipse/xtext/builder/standalone/TestableStandaloneBuilder.java
  org.eclipse.xtext.builder.standalone.tests/src/org/eclipse/xtext/builder/standalone/incremental/IncrementalStandaloneBuilderTest.java
  org.eclipse.xtext.builder.standalone.tests/src/org/eclipse/xtext/builder/standalone/incremental/IncrementalStandaloneBuilderWithJavaTest.java
  org.eclipse.xtext.builder.standalone.tests/src/org/eclipse/xtext/builder/tests/MyGenerator.java
  org.eclipse.xtext.builder.standalone.tests/test-data/ec-test/test-class/com/acme/BugsBunny.java
  org.eclipse.xtext.builder.standalone.tests/test-data/ec-test/test-class/com/acme/LoonyToon.java
  org.eclipse.xtext.builder.standalone.tests/test-data/standalone.incremental.java/src/com/acme/BugsBunny.java
  org.eclipse.xtext.builder.standalone.tests/test-data/standalone.incremental.java/src/com/acme/First.contentassistfragmenttestlang
  org.eclipse.xtext.builder.standalone.tests/test-data/standalone.incremental.java/src/com/acme/LoonyToon.java
  org.eclipse.xtext.builder.standalone.tests/test-data/standalone.incremental.java/src/com/acme/Second.contentassistfragmenttestlang
  org.eclipse.xtext.builder.standalone.tests/test-data/standalone.incremental.java/src/com/acme/Tweety.java
  org.eclipse.xtext.builder.standalone.tests/test-data/standalone.incremental/src/First.buildertestlanguage
  org.eclipse.xtext.builder.standalone.tests/test-data/standalone.incremental/src/Second.buildertestlanguage
  org.eclipse.xtext.builder.standalone/META-INF/MANIFEST.MF
  org.eclipse.xtext.builder.standalone/src/org/eclipse/xtext/builder/standalone/IIssueHandler.java
  org.eclipse.xtext.builder.standalone/src/org/eclipse/xtext/builder/standalone/StandaloneBuilder.java
  org.eclipse.xtext.builder.standalone/src/org/eclipse/xtext/builder/standalone/StandaloneBuilderFileCallback.java
  org.eclipse.xtext.builder.standalone/src/org/eclipse/xtext/builder/standalone/StandaloneBuilderState.java
  org.eclipse.xtext.builder.standalone/src/org/eclipse/xtext/builder/standalone/compiler/AccessibleReferenceCollection.java
  org.eclipse.xtext.builder.standalone/src/org/eclipse/xtext/builder/standalone/compiler/ClassFileEObjectDescription.java
  org.eclipse.xtext.builder.standalone/src/org/eclipse/xtext/builder/standalone/compiler/ClassFileResourceDescription.java
  org.eclipse.xtext.builder.standalone/src/org/eclipse/xtext/builder/standalone/compiler/CompilerConfiguration.java
  org.eclipse.xtext.builder.standalone/src/org/eclipse/xtext/builder/standalone/compiler/EclipseJavaCompiler.java
  org.eclipse.xtext.builder.standalone/src/org/eclipse/xtext/builder/standalone/compiler/InternalIncrementalCompiler.java
  org.eclipse.xtext.builder.standalone/src/org/eclipse/xtext/builder/standalone/compiler/SerializedCompilerState.java
  org.eclipse.xtext.builder.standalone/src/org/eclipse/xtext/builder/standalone/incremental/BinaryFileHashing.java
  org.eclipse.xtext.builder.standalone/src/org/eclipse/xtext/builder/standalone/incremental/ClasspathInfos.java
  org.eclipse.xtext.builder.standalone/src/org/eclipse/xtext/builder/standalone/incremental/ExtendedEObjectInputStream.java
  org.eclipse.xtext.builder.standalone/src/org/eclipse/xtext/builder/standalone/incremental/ExtendedEObjectOutputStream.java
  org.eclipse.xtext.xbase.testlanguages/src/org/eclipse/xtext/xbase/testlanguages/ContentAssistFragmentTestLangStandaloneSetup.java
Labels: new_feature

#813 [#805] Fixed accidentally broken semantic of failOnValidationError
  org.eclipse.xtext.builder.standalone/src/org/eclipse/xtext/builder/standalone/StandaloneBuilder.java
Labels: bug
