Repository eclipse/xtext-extras, pull requests merged in 2022-10, with the labels that each got.

#816 Fix Standalone Builder bugs
  org.eclipse.xtext.builder.standalone/META-INF/MANIFEST.MF
  org.eclipse.xtext.builder.standalone/src/org/eclipse/xtext/builder/standalone/StandaloneBuilder.java
Labels: bug

#817 [#805] Don't log exceptions when serializing the library index
  org.eclipse.xtext.builder.standalone/src/org/eclipse/xtext/builder/standalone/StandaloneBuilder.java
Labels: bug

#818 [#805] Don't blindly compile all source directories
  org.eclipse.xtext.builder.standalone/src/org/eclipse/xtext/builder/standalone/StandaloneBuilder.java
Labels: bug

#819 [releng] Bootstrap against 2.29.0.M1
  gradle/versions.gradle
Labels: releng, bot

#820 bump tycho bootstrapping
  releng/releng-target/xtext-extras.target.target
Labels: releng

#822 [eclipse/xtext#2104] update to asm 9.4
  NOTICE.md
  org.eclipse.xtext.common.types.tests/META-INF/MANIFEST.MF_gen
  org.eclipse.xtext.common.types/META-INF/MANIFEST.MF
  org.eclipse.xtext.common.types/src/org/eclipse/xtext/common/types/access/impl/DeclaredTypeFactory.java
  org.eclipse.xtext.generator/src/org/eclipse/xtext/generator/types/TypesGeneratorFragment.java
  org.eclipse.xtext.purexbase.tests/META-INF/MANIFEST.MF
  org.eclipse.xtext.purexbase/META-INF/MANIFEST.MF
  org.eclipse.xtext.xbase.ide/META-INF/MANIFEST.MF
  org.eclipse.xtext.xbase.testdata/META-INF/MANIFEST.MF
  org.eclipse.xtext.xbase.testlanguages/META-INF/MANIFEST.MF
  org.eclipse.xtext.xbase/META-INF/MANIFEST.MF
  releng/releng-target/xtext-extras.target.target
Labels: releng

#823 [releng] Bootstrap against 2.29.0.M2
  gradle/versions.gradle
Labels: releng, bot
