Repository eclipse/xtext-extras, pull requests merged in 2023-02, with the labels that each got.

#863 also drop simpleJar from gradle
  org.eclipse.xtext.extras.tests/build.gradle
Labels: releng

#860 [eclipse/xtext-xtend#1005] Performance improvements for type computation
  org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/typesystem/AbstractTypeResolverTest.java
  org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/typesystem/IResolvedTypes.java
  org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/typesystem/computation/ITypeComputationState.java
  org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/typesystem/internal/AbstractTypeComputationState.java
  org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/typesystem/internal/ExpressionAwareStackedResolvedTypes.java
  org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/typesystem/internal/ResolvedTypes.java
Labels: performance

#866 [releng] Bootstrap against 2.30.0.M3
  gradle/versions.gradle
Labels: releng, bot

#867 [eclipse/xtext-xtend#1005] Fixed regression in type inference
  org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/typesystem/internal/AbstractPendingLinkingCandidate.java
  org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/typesystem/internal/AbstractTypeComputationState.java
Labels: bug

#869 [releng] Bootstrap against 2.30.0.RC1
  gradle/versions.gradle
Labels: releng, bot

#868 [eclipse/xtext#2138] update to gradle 7.6.1
  gradle/wrapper/gradle-wrapper.properties
Labels: releng

#871 [releng] Bootstrap against 2.30.0.RC2
  gradle/versions.gradle
Labels: releng, bot

#872 [releng] Update Xtext version to 2.31.0
  gradle/versions.gradle
  org.eclipse.xtext.builder.standalone.tests/META-INF/MANIFEST.MF
  org.eclipse.xtext.builder.standalone/META-INF/MANIFEST.MF
  org.eclipse.xtext.common.types/META-INF/MANIFEST.MF
  org.eclipse.xtext.ecore/META-INF/MANIFEST.MF
  org.eclipse.xtext.extras.tests/META-INF/MANIFEST.MF
  org.eclipse.xtext.generator/META-INF/MANIFEST.MF
  org.eclipse.xtext.java/META-INF/MANIFEST.MF
  org.eclipse.xtext.purexbase.ide/META-INF/MANIFEST.MF
  org.eclipse.xtext.purexbase.tests/META-INF/MANIFEST.MF
  org.eclipse.xtext.purexbase/META-INF/MANIFEST.MF
  org.eclipse.xtext.smap/META-INF/MANIFEST.MF
  org.eclipse.xtext.xbase.ide/META-INF/MANIFEST.MF
  org.eclipse.xtext.xbase.testdata/META-INF/MANIFEST.MF
  org.eclipse.xtext.xbase.testing/META-INF/MANIFEST.MF
  org.eclipse.xtext.xbase.testlanguages.ide/META-INF/MANIFEST.MF
  org.eclipse.xtext.xbase.testlanguages/META-INF/MANIFEST.MF
  org.eclipse.xtext.xbase.tests/META-INF/MANIFEST.MF
  org.eclipse.xtext.xbase/META-INF/MANIFEST.MF
  releng/p2/category.xml
  releng/p2/pom.xml
  releng/pom.xml
  releng/releng-target/pom.xml
Labels: releng, bot

#873 [releng] Bootstrap against 2.30.0
  gradle/versions.gradle
Labels: releng, bot
